//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_back_end.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string titleComment { get; set; }
        public string contentComment { get; set; }
        public string fbName { get; set; }
        public string dateTime { get; set; }
        public int school_id { get; set; }
    
        public virtual schools schools { get; set; }
    }
}
