//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master_back_end.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class schools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schools()
        {
            this.comment = new HashSet<comment>();
            this.recension = new HashSet<recension>();
        }
    
        public int school_id { get; set; }
        public string id { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string pbroj { get; set; }
        public string mesto { get; set; }
        public string opstina { get; set; }
        public string okrug { get; set; }
        public string suprava { get; set; }
        public string www { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string vrsta { get; set; }
        public string odeljenja { get; set; }
        public string gps { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recension> recension { get; set; }
    }
}
